const fido = () => {
    var publicKey = {
        challenge: new Uint8Array([21,31,105 /* 29 more random bytes generated by the server */]),
      
        rp: {
          name: "ACME Corporation"
        },
      
        user: {
          id: Uint8Array.from(window.atob("MIIBkzCCATigAwIBAjCCAZMwggE4oAMCAQIwggGTMII="), c=>c.charCodeAt(0)),
          name: "alex.mueller@example.com",
          displayName: "Alex Müller",
        },
      
        pubKeyCredParams: [
          { type: "public-key", alg: -7 },
          { type: "public-key", alg: -257 }
        ],
      
        authenticatorSelection: {

          userVerification: "preferred"
        },
      
        timeout: 300000,  // 5 minutes
        excludeCredentials: [

          {"id": Uint8Array.from(window.atob("ufJWp8YGlibm1Kd9XQBWN1WAw2jy5In2Xhon9HAqcXE="), c=>c.charCodeAt(0)), "type": "public-key"},
          {"id": Uint8Array.from(window.atob("E/e1dhZc++mIsz4f9hb6NifAzJpF1V4mEtRlIPBiWdY="), c=>c.charCodeAt(0)), "type": "public-key"}
        ],
      
        extensions: {"appidExclude": "https://acme.example.com"}
      };

      navigator.credentials.get({publicKey})
      
}
export default fido;